### ISSUE TITLE
Remove link duplication from Community page metadata

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#480]
Since [v0.86.0] of Hugo, render-link hooks are [applied to all links](https://github.com/gohugoio/hugo/issues/8755), this gives us an opportunity to remove link duplication from the Community card-lists metadata.

For example, consider:

```yaml
main_channels:
  title: >
      <a href="https://groups.google.com/forum/?hl=en#!forum/etcd-dev" target="_blank" rel="noopener"><i class="fab fa-google"></i>&nbsp;Google Group</a>
  desc: >
      Join the [etcd-dev][] forum to ask questions and get the latest etcd news.
```

Note that the Google Group link appears in both the `title` (hard coded) and in the `[etcd-dev]` link definition -- and this duplication lead to #466 and #481.

[v0.86.0]: https://github.com/gohugoio/hugo/releases/tag/v0.86.0
