### ISSUE TITLE
Remove all references to `rkt` in documentation

### ISSUE THREAD

**Issue by linghengqian** [etcd-io/website#912]
- https://github.com/rkt/rkt has been archived since `Feb 25, 2020`, and has been out of development for years. I think it's inappropriate that documents like https://etcd.io/docs/v3.5/op-guide/container/ still refer to `rkt`.

> rkt
> Running a single node etcd
> The following rkt run command will expose the etcd client API on port 2379 and expose the peer API on port 2380.

- I think it's enough for us to just keep the documentation for the Docker part. 
- Or we can also add additional documentation for Docker Compose. Projects like https://github.com/etcd-io/jetcd like to use `0.0.0.0` as the `ip`, which is hardly mentioned in the current documentation. This leads to misunderstandings like https://github.com/apache/shardingsphere/issues/33565 .
```yaml
services:
  etcd-test:
    image: gcr.io/etcd-development/etcd:v3.5.10
    command: [ "etcd", "--name", "etcd0", "--advertise-client-urls", "http://0.0.0.0:2379", "--listen-client-urls", "http://0.0.0.0:2379", "--data-dir", "/tmp/etcd-data" ]
    environment:
      ETCD_LOG_LEVEL: info
      ETCD_LOGGER: zap
    expose:
      - 2379
      - 2380
```
